Add preview for "./bin/config down"

diff --git a/bin/config b/bin/config
--- a/bin/config
+++ b/bin/config
@@ -7,14 +7,6 @@ set -eu -o pipefail # Exit on pipe failure
 #
 # To git started, you can run ./bin/config help
 
-# unmake_link <src> <dst>
-#
-# Remove an existing link from <src> to <dst>.
-unmake_link() {
-    echo "Unlinking $1 from $2: done"
-    rm $2
-}
-
 SRC_DEFAULT_DIR="$PWD/home" # This is chosen so running bin/config up "just works"
 
 DST_DEFAULT_DIR="$HOME"
@@ -158,6 +150,7 @@ make_link () {
             echo "Failed to link $2 to $3"
         fi
     elif [[ "$5" = - ]]; then
+        echo "Removing $3"
         rm "$3"
     fi
 }
@@ -175,31 +168,19 @@ preview_make_link () {
     fi
 }
 
-# TODO: Reimplement stand_up in terms of traverse_directory standup_helper. Then
-# re-implement tear_down the same way. We should see a similar diff semantic, with `-` for
-# remove.
+# tear_down <command> <path> <depth>
 #
-# We can parameterize stand_up_helper with a payload arg that is expanded when passed to
-# stand_up_helper.
-
-
-# tear_down <path> <unlink: fn(src, dst)>
+# <command> takes the same arguments as it does in stand_up
 tear_down () {
-    if [[ -L "$DST_DIR/$1" ]] && [[ "$(readlink $DST_DIR/$1)" == "$SRC_DIR/$1" ]]; then
+    if [[ -L "$DST_DIR/$2" ]] && [[ "$(readlink $DST_DIR/$2)" == "$SRC_DIR/$2" ]]; then
 	# Its a link to the file in our tree
-	$2 "$SRC_DIR/$1" "$DST_DIR/$1"
-    elif [[ -d "$DST_DIR/$1" ]] && [[ -d "$SRC_DIR/$1" ]]; then
-	# The dst directory exists,
-	for entry in $('ls' -a "$SRC_DIR/$1"); do
-	    if [[ "$entry" == "." ]] || [[ "$entry" == ".." ]]; then
-		true # do nothing here
-	    elif [[ "$1" == "" ]]; then
-		tear_down "$entry" $2
-	    else
-		tear_down "$1/$entry" $2
-	    fi
-	done
+	$1 "$2" "$SRC_DIR/$1" "$DST_DIR/$1" "$3" -
+    elif [[ -d "$DST_DIR/$2" ]] && [[ -d "$SRC_DIR/$2" ]]; then
+	# The dst directory exists, but not as a link. We recurse
+	$1 "$2" "$SRC_DIR/$1" "$DST_DIR/$1" "$3" n
+        return 0
     fi
+    return 1
 }
 
 USER_LOCAL_PATH="$PWD/.local"
@@ -219,8 +200,8 @@ ensure_initialized () {
 # $1 is the direction, either "clean" or "smudge".
 apply_identity () {
     if ! [[ -f $USER_IDENTITY_PATH ]]; then
-       echo "internal error: Missing identity filter"
-       exit 1
+        echo "internal error: Missing identity filter"
+        exit 1
     fi
 
     for file in $(find home -type f); do
@@ -229,26 +210,39 @@ apply_identity () {
         # Because the shell does funny things with newlines, we manually check if the
         # newline exists and re-apply it if it does.
         if [[ $(tail -c1 "$file" | wc -l) -gt 0 ]]; then
-           eof="\n"
+            eof="\n"
         else
-           eof=''
+            eof=''
         fi
 
         printf '%s' "$content" | $USER_IDENTITY_PATH $1 > $file
         if [[ "$eof" == "\n" ]]; then
-           printf "$eof" >> $file
+            printf "$eof" >> $file
         fi
 
         # `git status` still shows changed files as "dirty", even when `git diff` shows
         # them as clean. We add such files to `git status` comes up clean as expected.
         if [[ "$(git diff $file)" = "" ]]; then
-           git add $file
+            git add $file
         fi
     done
 }
 
+confirm () {
+    while true; do
+        read -p "Are you sure? " yn
+        case $yn in
+            [Yy]* ) return 0; break;;
+            [Nn]* ) return 1; break;;
+            * ) echo "Please answer yes or no.";;
+        esac
+    done
+}
+
+
+
 if [[ $# -eq 0 ]]; then
-	echo "$HELP"
+    echo "$HELP"
 fi
 
 case $1 in
@@ -256,11 +250,20 @@ case $1 in
         ensure_initialized
         traverse_directory "stand_up preview_make_link" "" | column -t -s @
 
-        echo "Now linking"
-        traverse_directory "stand_up make_link" ""
+        if confirm; then
+            traverse_directory "stand_up make_link" ""
+        else
+            echo "Canceled"
+        fi
 	;;
     down)
-	tear_down "" unmake_link
+	traverse_directory "tear_down preview_make_link" "" | column -t -s @
+
+        if confirm; then
+            traverse_directory "tear_down make_link" ""
+        else
+            echo "Canceled"
+        fi
 	;;
     init)
         read -p 'What is your full name (example "Jane Smith")? ' USER_NAME
