Add tree and preview to `./bin/config` (#2)
* WIP re-implement linking

* Implement stand_up in terms of traverse_directory

* Add preview for "./bin/config down"

* Fix dst dir for teardown

diff --git a/bin/config b/bin/config
--- a/bin/config
+++ b/bin/config
@@ -1,65 +1,39 @@
 #!/usr/bin/env sh
 
+set -eu -o pipefail # Exit on pipe failure
+
 # The script used to apply the config in this repository to the host computer and to
 # remove the applied config from the host computer.
 #
 # To git started, you can run ./bin/config help
 
-# make_link <src> <dst>
-#
-# Create a link between <src> and <dst>.
-# <src> may be a directory.
-# <dst> will not exist.
-#
-# You can override the command used by setting CONFIG_LINK_CMD.
-make_link () {
-    if [[ "" == "$CONFIG_LINK_CMD" ]]; then
-	echo "Linking $1 to $2: done"
-	ln -s -w $1 $2
-    else
-	$CONFIG_LINK_CMD $1 $2
-    fi
-}
-
-# unmake_link <src> <dst>
-#
-# Remove an existing link from <src> to <dst>.
-#
-# You can override the command used by setting CONFIG_UNLINK_CMD.
-unmake_link() {
-    if [[ "" == "$CONFIG_UNLINK_CMD" ]]; then
-	echo "Unlinking $1 from $2: done"
-	rm $2
-    else
-	$CONFIG_UNLINK_CMD $1 $2
-    fi
-}
-
-# skip_link <src> <dst>
-#
-# Skip linking from <src> to <dst> because <dst> already exists.
-skip_link() {
-    # echo "skiping linking $1 to $2"
-    true # Necessary because empty functions are not allowed in sh scripts.
-}
-
 SRC_DEFAULT_DIR="$PWD/home" # This is chosen so running bin/config up "just works"
 
 DST_DEFAULT_DIR="$HOME"
 
-read -r -d '' HELP <<- EOF
+# This is necessary because `read` hits EOF, which causes a non-zero exit code.
+read -r -d '' HELP <<- EOF || true
 	config [up|down|init] [src=$SRC_DEFAULT_DIR] [dst=$DST_DEFAULT_DIR]
 
 	Recursivly link src to dst. Effert is made to make the minimum number of links.
-	That means that directories are linked if possible, otherwise their content is recursed.
+	That means that directories are linked if possible, otherwise their content is
+	recursed.
 
 	Files in dst are prioritized over files in src.
 
 	Both src and dst must be directories.
 EOF
 
-SRC_DIR=$2
-DST_DIR=$3
+SRC_DIR=""
+DST_DIR=""
+
+if [ $# -gt 1 ]; then
+    SRC_DIR=$2
+fi
+if [ $# -gt 2 ]; then
+    DST_DIR=$3
+fi
+
 
 if [[ "$SRC_DIR" == "" ]]; then
     # If the source directory is empty, apply the default.
@@ -73,8 +47,8 @@ fi
 if [[ "$DST_DIR" == "" ]]; then
     DST_DIR="$DST_DEFAULT_DIR"
 elif [[ ! "$DST_DIR" == /* ]]; then
-     # If a relative directory was given, set it relative to the current directory.
-     DST_DIR="$PWD/$DST_DIR"
+    # If a relative directory was given, set it relative to the current directory.
+    DST_DIR="$PWD/$DST_DIR"
 fi
 
 if [[ ! -d "$SRC_DIR" ]]; then
@@ -91,48 +65,122 @@ if [[ ! -d "$DST_DIR" ]]; then
     exit 1
 fi
 
-# stand_up <path>
-stand_up () {
-    if [[ ! -e "$DST_DIR/$1" ]] && [[ ! -L "$DST_DIR/$1" ]]; then
-	# dst doesn't exist, so link the entry.  This can be either a file or a
-	# directory.
-	make_link "$SRC_DIR/$1" "$DST_DIR/$1"
-    elif [[ -d "$DST_DIR/$1" ]] && [[ -d "$SRC_DIR/$1" ]]; then
-	# The dst directory exists,
-	for entry in $('ls' -a "$SRC_DIR/$1"); do
+# indent_to <depth> <item>
+#
+# Print tree characters to look like:
+#
+# |-- top_level/         # indent_to 0 "top_level/"
+# |   |-- second         # indent_to 1 "second"
+# |-- third/             # indent_to 0 "third/"
+# |   |-- fourth         # indent_to 1 "fourth"
+# |   |-- counting/      # indent_to 1 "counting/"
+# |   |   |-- is/        # indent_to 2 "is/"
+# |   |   |   |-- hard   # indent_to 3 "hard"
+indent_to () {
+    one_less=$(( $1 - 1 ))
+    while [[ $one_less -gt 0 ]]; do
+        one_less=$(( $one_less - 1 ))
+        printf "|   "
+    done
+    printf "|-- %s\n" "$2"
+}
+
+# traverse_directory <helper: fn(path, depth)->should_recurse> <path> <depth>
+#
+# <helper> is intentionally not quoted when it is called, allowing users to pass in a
+# function and initial arguments. This is valid:
+#
+#     traverse_directory "helper initial_arg" $path $depth
+#
+# When "helper" is called, $1 will be "initial_arg".
+traverse_directory () {
+    local depth
+    if [[ "$#" -lt 3 ]]; then
+        depth=0
+    else
+        depth=$3
+    fi
+    if eval $1 \""$2"\" $depth; then
+        for entry in $('ls' -a "$SRC_DIR/$2"); do
 	    if [[ "$entry" == "." ]] || [[ "$entry" == ".." ]]; then
 		true # do nothing here
-	    elif [[ "$1" == "" ]]; then
-		stand_up "$entry"
+	    elif [[ "$2" == "" ]]; then
+		traverse_directory  "$1" "$entry" $(( $depth + 1 ))
 	    else
-		stand_up "$1/$entry"
+		traverse_directory "$1" "$2/$entry" $(( $depth + 1 ))
             fi
 	done
-    elif [[ -L "$DST_DIR/$1" ]] && [[ "$(readlink $DST_DIR/$1)" == "$SRC_DIR/$1" ]]; then
-	echo "Linking $DST_DIR/$1: already linked"
-    else
-	# We can't recurse down directories, so we give up
-	skip_link "$SRC_DIR/$1" "$DST_DIR/$1"
     fi
 }
 
-# tear_down <path>
-tear_down () {
-    if [[ -L "$DST_DIR/$1" ]] && [[ "$(readlink $DST_DIR/$1)" == "$SRC_DIR/$1" ]]; then
-	# Its a link to the file in our tree
-	unmake_link "$SRC_DIR/$1" "$DST_DIR/$1"
-    elif [[ -d "$DST_DIR/$1" ]] && [[ -d "$SRC_DIR/$1" ]]; then
-	# The dst directory exists,
-	for entry in $('ls' -a "$SRC_DIR/$1"); do
-	    if [[ "$entry" == "." ]] || [[ "$entry" == ".." ]]; then
-		true # do nothing here
-	    elif [[ "$1" == "" ]]; then
-		tear_down "$entry"
-	    else
-		tear_down "$1/$entry"
-	    fi
-	done
+# stand_up <command> <path> <depth>
+#
+# <command> is itself a function that actually performs the linking.
+# It takes as arguments:
+#   <base>  : The path segment we are looking at
+#   <src>   : The path to the source
+#   <dst>   : The path to the destination
+#   <depth> : The depth in the tree
+#   <kind>  : The kind of operation we expect: [~|+|n|-]
+#             ~ means already linked, so no op
+#             + means link
+#             n no applicable operation
+#             - remove link
+stand_up () {
+    if [[ ! -e "$DST_DIR/$2" ]] && [[ ! -L "$DST_DIR/$2" ]]; then
+	# dst doesn't exist, so link the entry.  This can be either a file or a
+	# directory.
+	$1 "$2" "$SRC_DIR/$2" "$DST_DIR/$2" "$3" +
+    elif [[ -L "$DST_DIR/$2" ]] && [[ "$(readlink $DST_DIR/$2)" == "$SRC_DIR/$2" ]]; then
+        $1 "$2" "$SRC_DIR/$2" "$DST_DIR/$2" "$3" '~'
+    elif [[ -d "$DST_DIR/$2" ]] && [[ -d "$SRC_DIR/$2" ]]; then
+        $1 "$2" "$SRC_DIR/$2" "$DST_DIR/$2" "$3" n
+	return 0 # Recurse
     fi
+    return 1 # Don't recurse
+}
+
+# make_link <base> <src> <dst> <depth> <kind>
+#
+# A potential argument for stand_up_helper
+make_link () {
+    if [[ "$5" = + ]]; then
+        echo "Linking $1 to $3"
+        if ! ln -s -w $2 $3; then
+            echo "Failed to link $2 to $3"
+        fi
+    elif [[ "$5" = - ]]; then
+        echo "Removing $3"
+        rm "$3"
+    fi
+}
+
+# preview_make_link <base> <src> <dst> <depth> <kind>
+#
+# A potential argument for stand_up_helper
+preview_make_link () {
+    if [[ "$1" = "" ]]; then
+        echo "$SRC_DIR/ -> $DST_DIR/"
+    elif [[ "$5" = n ]]; then
+        indent_to "$4" "$1"
+    else
+        indent_to "$4" "$1 @ $5"
+    fi
+}
+
+# tear_down <command> <path> <depth>
+#
+# <command> takes the same arguments as it does in stand_up
+tear_down () {
+    if [[ -L "$DST_DIR/$2" ]] && [[ "$(readlink $DST_DIR/$2)" == "$SRC_DIR/$2" ]]; then
+	# Its a link to the file in our tree
+	$1 "$2" "$SRC_DIR/$1" "$DST_DIR/$2" "$3" -
+    elif [[ -d "$DST_DIR/$2" ]] && [[ -d "$SRC_DIR/$2" ]]; then
+	# The dst directory exists, but not as a link. We recurse
+	$1 "$2" "$SRC_DIR/$1" "$DST_DIR/$2" "$3" n
+        return 0
+    fi
+    return 1
 }
 
 USER_LOCAL_PATH="$PWD/.local"
@@ -152,8 +200,8 @@ ensure_initialized () {
 # $1 is the direction, either "clean" or "smudge".
 apply_identity () {
     if ! [[ -f $USER_IDENTITY_PATH ]]; then
-       echo "internal error: Missing identity filter"
-       exit 1
+        echo "internal error: Missing identity filter"
+        exit 1
     fi
 
     for file in $(find home -type f); do
@@ -162,31 +210,60 @@ apply_identity () {
         # Because the shell does funny things with newlines, we manually check if the
         # newline exists and re-apply it if it does.
         if [[ $(tail -c1 "$file" | wc -l) -gt 0 ]]; then
-           eof="\n"
+            eof="\n"
         else
-           eof=''
+            eof=''
         fi
 
         printf '%s' "$content" | $USER_IDENTITY_PATH $1 > $file
         if [[ "$eof" == "\n" ]]; then
-           printf "$eof" >> $file
+            printf "$eof" >> $file
         fi
 
         # `git status` still shows changed files as "dirty", even when `git diff` shows
         # them as clean. We add such files to `git status` comes up clean as expected.
         if [[ "$(git diff $file)" = "" ]]; then
-           git add $file
+            git add $file
         fi
     done
 }
 
+confirm () {
+    while true; do
+        read -p "Are you sure? " yn
+        case $yn in
+            [Yy]* ) return 0; break;;
+            [Nn]* ) return 1; break;;
+            * ) echo "Please answer yes or no.";;
+        esac
+    done
+}
+
+
+
+if [[ $# -eq 0 ]]; then
+    echo "$HELP"
+fi
+
 case $1 in
     up)
         ensure_initialized
-	stand_up ""
+        traverse_directory "stand_up preview_make_link" "" | column -t -s @
+
+        if confirm; then
+            traverse_directory "stand_up make_link" ""
+        else
+            echo "Canceled"
+        fi
 	;;
     down)
-	tear_down ""
+	traverse_directory "tear_down preview_make_link" "" | column -t -s @
+
+        if confirm; then
+            traverse_directory "tear_down make_link" ""
+        else
+            echo "Canceled"
+        fi
 	;;
     init)
         read -p 'What is your full name (example "Jane Smith")? ' USER_NAME
