Make fonts user configurable

diff --git a/bin/config b/bin/config
--- a/bin/config
+++ b/bin/config
@@ -183,6 +183,65 @@ USER_LOCAL_PATH="$PWD/.local"
 USER_DATA_PATH="$USER_LOCAL_PATH/user-data.sh"
 USER_IDENTITY_PATH="$USER_LOCAL_PATH/identity.sh"
 
+IDENTITY_VARS=$(cat <<EOF
+USER_NAME='What is your full name (example "Jane Smith")? '
+USER_EMAIL='What is your email address? '
+USER_FONT='What is your preferred font? '
+EOF
+             )
+
+# sed_identity_filter <direction>
+sed_identity_filter () {
+    sep=""
+    printf '%s' "$IDENTITY_VARS" | while IFS= read -r line || [ -n "$line" ]
+    do
+        var=${line%=*}
+        case "$1" in
+            clean)
+                before=$(eval "echo $"$var"")
+                after="$var"
+                ;;
+            smudge)
+                before="$var"
+                after=$(eval "echo $"$var"")
+                ;;
+            *)
+                echo "Invalid $0 arg: $1"
+                exit 1
+                ;;
+        esac
+        printf "%ssed 's/%s/%s/'" "$sep" "$before" "$after"
+        sep=" | "
+    done
+    echo ""
+}
+
+# Ask the user to set $IDENTITY_VARS data.
+ask_user_data () {
+    oldIFS="$IFS"
+    IFS="
+"
+    for line in $IDENTITY_VARS; do
+        var=${line%=*}
+        query=${line#*=}
+        eval "printf $query"
+        read -r "${var?}"
+    done
+    IFS="$oldIFS"
+    return 0
+}
+
+# Write user data variables to $USER_DATA_PATH.
+write_user_data () {
+    mkdir -p "$USER_LOCAL_PATH"
+    echo "# This file is generated by $0. Only edit if you know what you are doing." > "$USER_DATA_PATH"
+    printf '%s' "$IDENTITY_VARS" | while IFS= read -r line || [ -n "$line" ]
+    do
+        var=${line%=*}
+        printf '%s="%s"\n' "$var" "$(eval "echo $"$var"")" >> "$USER_DATA_PATH"
+    done
+}
+
 ensure_initialized () {
     if [ -f "$USER_DATA_PATH" ]; then
         . "$USER_DATA_PATH"
@@ -262,8 +321,10 @@ case $1 in
         fi
 	;;
     init)
-        read -p 'What is your full name (example "Jane Smith")? ' USER_NAME
-        read -p 'What is your email address? ' USER_EMAIL
+        if ! ask_user_data; then
+            echo "Canceled"
+            exit 1
+        fi
 
         # If the user has already set this up, remove the previous identity so the new
         # identity applies cleanly.
@@ -271,12 +332,8 @@ case $1 in
            apply_identity clean
         fi
 
-        mkdir -p "$USER_LOCAL_PATH"
-        cat<<-EOF > "$USER_DATA_PATH"
-# This file is generated by $0. Only edit if you know what you are doing.
-USER_NAME="$USER_NAME"
-USER_EMAIL="$USER_EMAIL"
-EOF
+        write_user_data
+
         cat<<-EOF > "$USER_IDENTITY_PATH"
 #!/usr/bin/env sh
 
@@ -284,13 +341,13 @@ EOF
 
 case \$1 in
      clean)
-        sed 's/$USER_NAME/USER_NAME/g' | sed 's/$USER_EMAIL/USER_EMAIL/g'
+        $(sed_identity_filter clean)
         ;;
      smudge)
-        sed 's/USER_NAME/$USER_NAME/g' | sed 's/USER_EMAIL/$USER_EMAIL/g'
+        $(sed_identity_filter smudge)
         ;;
      *)
-        echo "Unknown command \\\"\$1\\\""
+        echo "Unknown command \\"\$1\\""
         exit 1
         ;;
 esac
