Remove existing identity filter before applying a new one

diff --git a/bin/config b/bin/config
--- a/bin/config
+++ b/bin/config
@@ -140,12 +140,38 @@ USER_DATA_PATH="$USER_LOCAL_PATH/user-data.sh"
 USER_IDENTITY_PATH="$USER_LOCAL_PATH/identity.sh"
 
 ensure_initialized () {
-if [ -f $USER_DATA_PATH ]; then
-source "$USER_DATA_PATH"
-else
-echo "Please run '$0 init' before attempting to link in files."
-exit 1
-fi
+    if [ -f $USER_DATA_PATH ]; then
+        source "$USER_DATA_PATH"
+    else
+        echo "Please run '$0 init' before attempting to link in files."
+        exit 1
+    fi
+}
+
+# Apply the identity filter.
+# $1 is the direction, either "clean" or "smudge".
+apply_identity () {
+    if ! [[ -f $USER_IDENTITY_PATH ]]; then
+       echo "internal error: Missing identity filter"
+       exit 1
+    fi
+
+    for file in $(find home -type f); do
+        content=$(cat "$file")
+
+        # Because the shell does funny things with newlines, we manually check if the
+        # newline exists and re-apply it if it does.
+        if [[ $(tail -c1 "$file" | wc -l) -gt 0 ]]; then
+           eof="\n"
+        else
+           eof=''
+        fi
+
+        printf '%s' "$content" | $USER_IDENTITY_PATH $1 > $file
+        if [[ "$eof" == "\n" ]]; then
+           printf "$eof" >> $file
+        fi
+    done
 }
 
 case $1 in
@@ -159,6 +185,13 @@ case $1 in
     init)
         read -p 'What is your full name (example "Jane Smith")? ' USER_NAME
         read -p 'What is your email address? ' USER_EMAIL
+
+        # If the user has already set this up, remove the previous identity so the new
+        # identity applies cleanly.
+        if [[ -f $USER_IDENTITY_PATH ]]; then
+           apply_identity clean
+        fi
+
         mkdir -p $USER_LOCAL_PATH
         cat<<-EOF > $USER_DATA_PATH
 # This file is generated by $0. Only edit if you know what you are doing.
@@ -194,22 +227,7 @@ EOF
         git config filter.identity.smudge "$USER_IDENTITY_PATH smudge"
 
         # Now apply the identity filter we have just created manually
-        for file in $(find home -type f); do
-            content=$(cat "$file")
-
-            # Because the shell does funny things with newlines, we manually check if the
-            # newline exists and re-apply it if it does.
-            if [[ $(tail -c1 "$file" | wc -l) -gt 0 ]]; then
-               eof="\n"
-            else
-               eof=''
-            fi
-
-            printf '%s' "$content" | $USER_IDENTITY_PATH smudge > $file
-            if [[ "$eof" == "\n" ]]; then
-               printf "$eof" >> $file
-            fi
-        done
+        apply_identity smudge
         ;;
     *)
 	echo "Unknown command \"$1\""
